"""initial_schema

Revision ID: 342bd09e76a5
Revises: 
Create Date: 2026-09-29 19:59:56.598760

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '342bd09e76a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('LOCAL', 'STATE', 'CENTRAL', name='authority_type'), nullable=False),
    sa.Column('jurisdiction', sa.String(length=255), nullable=False),
    sa.Column('parent_authority_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_authority_id'], ['authorities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorities_name'), 'authorities', ['name'], unique=True)
    op.create_index(op.f('ix_authorities_parent_authority_id'), 'authorities', ['parent_authority_id'], unique=False)
    op.create_index(op.f('ix_authorities_type'), 'authorities', ['type'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('keycloak_sub', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('authority_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_authority_id'), 'users', ['authority_id'], unique=False)
    op.create_index(op.f('ix_users_badge_id'), 'users', ['badge_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_keycloak_sub'), 'users', ['keycloak_sub'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(length=100), nullable=False),
    sa.Column('fir_number', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('crime_type', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'UNDER_ANALYSIS', 'PENDING_REVIEW', 'CLOSED', 'RESOLVED', name='case_status'), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='priority_level'), nullable=False),
    sa.Column('police_station', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('investigating_officer_id', sa.UUID(), nullable=False),
    sa.Column('authority_id', sa.UUID(), nullable=False),
    sa.Column('requires_attention', sa.Boolean(), nullable=False),
    sa.Column('attention_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['investigating_officer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_authority_id'), 'cases', ['authority_id'], unique=False)
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_crime_type'), 'cases', ['crime_type'], unique=False)
    op.create_index(op.f('ix_cases_fir_number'), 'cases', ['fir_number'], unique=False)
    op.create_index(op.f('ix_cases_investigating_officer_id'), 'cases', ['investigating_officer_id'], unique=False)
    op.create_index(op.f('ix_cases_priority'), 'cases', ['priority'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_case_id'), 'audit_log', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('case_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('role_in_case', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.Enum('VERIFIED_RECORD', 'SYSTEM_DERIVED', 'AI_ANALYSIS', name='source_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_entities_case_id'), 'case_entities', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_entities_entity_id'), 'case_entities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_case_entities_entity_type'), 'case_entities', ['entity_type'], unique=False)
    op.create_table('data_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_number', sa.String(length=100), nullable=False),
    sa.Column('requesting_authority_id', sa.UUID(), nullable=False),
    sa.Column('source_authority_id', sa.UUID(), nullable=False),
    sa.Column('requesting_officer_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('requested_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('urgency', sa.Enum('HIGH', 'ROUTINE', name='urgency_level'), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Under_Review', 'Approved', 'Rejected', 'Data_Sent', 'Received', name='data_request_status'), nullable=False),
    sa.Column('access_duration', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requesting_authority_id'], ['authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requesting_officer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_authority_id'], ['authorities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_requests_case_id'), 'data_requests', ['case_id'], unique=False)
    op.create_index(op.f('ix_data_requests_created_at'), 'data_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_requests_request_number'), 'data_requests', ['request_number'], unique=True)
    op.create_index(op.f('ix_data_requests_requesting_authority_id'), 'data_requests', ['requesting_authority_id'], unique=False)
    op.create_index(op.f('ix_data_requests_requesting_officer_id'), 'data_requests', ['requesting_officer_id'], unique=False)
    op.create_index(op.f('ix_data_requests_source_authority_id'), 'data_requests', ['source_authority_id'], unique=False)
    op.create_index(op.f('ix_data_requests_status'), 'data_requests', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('processing_status', sa.Enum('Processing', 'Processed', 'Failed', name='document_status'), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_documents_processing_status'), 'documents', ['processing_status'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('entity_a_id', sa.String(length=100), nullable=False),
    sa.Column('entity_a_name', sa.String(length=255), nullable=False),
    sa.Column('entity_a_type', sa.String(length=50), nullable=False),
    sa.Column('entity_b_id', sa.String(length=100), nullable=False),
    sa.Column('entity_b_name', sa.String(length=255), nullable=False),
    sa.Column('entity_b_type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('calibrated_probability', sa.Float(), nullable=False),
    sa.Column('evidence_strength', sa.Enum('Strong', 'Moderate', 'Limited', name='evidence_strength'), nullable=False),
    sa.Column('connection_basis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_basis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shap_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'CONFIRMED', 'DISMISSED', name='prediction_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_case_id'), 'ml_predictions', ['case_id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_created_at'), 'ml_predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ml_predictions_entity_a_id'), 'ml_predictions', ['entity_a_id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_entity_b_id'), 'ml_predictions', ['entity_b_id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_evidence_strength'), 'ml_predictions', ['evidence_strength'], unique=False)
    op.create_index(op.f('ix_ml_predictions_status'), 'ml_predictions', ['status'], unique=False)
    op.create_table('extracted_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('raw_value', sa.String(length=255), nullable=False),
    sa.Column('normalized_value', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_entities_case_id'), 'extracted_entities', ['case_id'], unique=False)
    op.create_index(op.f('ix_extracted_entities_confirmed'), 'extracted_entities', ['confirmed'], unique=False)
    op.create_index(op.f('ix_extracted_entities_confirmed_by'), 'extracted_entities', ['confirmed_by'], unique=False)
    op.create_index(op.f('ix_extracted_entities_document_id'), 'extracted_entities', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_entities_entity_type'), 'extracted_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_extracted_entities_rejected'), 'extracted_entities', ['rejected'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source_type', sa.Enum('VERIFIED_RECORD', 'SYSTEM_DERIVED', 'AI_ANALYSIS', name='source_type'), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('evidence_basis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_city'), 'locations', ['city'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_index(op.f('ix_locations_source_document_id'), 'locations', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_locations_source_type'), 'locations', ['source_type'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('national_id', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('SUSPECT', 'PERSON_OF_INTEREST', 'ASSOCIATE', 'WITNESS', 'VICTIM', name='person_status'), nullable=False),
    sa.Column('risk_level', sa.Enum('HIGH', 'ELEVATED', 'STANDARD', 'LOW', name='risk_level'), nullable=False),
    sa.Column('primary_address', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('VERIFIED_RECORD', 'SYSTEM_DERIVED', 'AI_ANALYSIS', name='source_type'), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('evidence_basis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_full_name'), 'persons', ['full_name'], unique=False)
    op.create_index(op.f('ix_persons_national_id'), 'persons', ['national_id'], unique=False)
    op.create_index(op.f('ix_persons_person_id'), 'persons', ['person_id'], unique=True)
    op.create_index(op.f('ix_persons_risk_level'), 'persons', ['risk_level'], unique=False)
    op.create_index(op.f('ix_persons_source_document_id'), 'persons', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_persons_source_type'), 'persons', ['source_type'], unique=False)
    op.create_index(op.f('ix_persons_status'), 'persons', ['status'], unique=False)
    op.create_table('shared_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_request_id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=False),
    sa.Column('record_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('access_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shared_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_request_id'], ['data_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_records_data_request_id'), 'shared_records', ['data_request_id'], unique=False)
    op.create_index(op.f('ix_shared_records_shared_by'), 'shared_records', ['shared_by'], unique=False)
    op.create_table('phone_numbers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('subscriber_name', sa.String(length=255), nullable=True),
    sa.Column('telecom_carrier', sa.String(length=100), nullable=True),
    sa.Column('associated_person_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.Enum('VERIFIED_RECORD', 'SYSTEM_DERIVED', 'AI_ANALYSIS', name='source_type'), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('evidence_basis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['associated_person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_numbers_associated_person_id'), 'phone_numbers', ['associated_person_id'], unique=False)
    op.create_index(op.f('ix_phone_numbers_phone_number'), 'phone_numbers', ['phone_number'], unique=False)
    op.create_index(op.f('ix_phone_numbers_source_document_id'), 'phone_numbers', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_phone_numbers_source_type'), 'phone_numbers', ['source_type'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(length=50), nullable=False),
    sa.Column('make_model', sa.String(length=100), nullable=True),
    sa.Column('chassis_number', sa.String(length=100), nullable=True),
    sa.Column('owner_person_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.Enum('VERIFIED_RECORD', 'SYSTEM_DERIVED', 'AI_ANALYSIS', name='source_type'), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('evidence_basis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_chassis_number'), 'vehicles', ['chassis_number'], unique=False)
    op.create_index(op.f('ix_vehicles_owner_person_id'), 'vehicles', ['owner_person_id'], unique=False)
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=False)
    op.create_index(op.f('ix_vehicles_source_document_id'), 'vehicles', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_vehicles_source_type'), 'vehicles', ['source_type'], unique=False)
    
    # Append-only enforcement trigger for audit_log
    op.execute("""
    CREATE OR REPLACE FUNCTION enforce_audit_log_append_only()
    RETURNS TRIGGER AS $$
    BEGIN
        RAISE EXCEPTION 'Audit log is strictly append-only. Modification or deletion is legally prohibited under statutory audit standards.';
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE OR REPLACE TRIGGER trg_audit_log_immutable
    BEFORE UPDATE OR DELETE ON audit_log
    FOR EACH ROW
    EXECUTE FUNCTION enforce_audit_log_append_only();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_log_immutable ON audit_log;")
    op.execute("DROP FUNCTION IF EXISTS enforce_audit_log_append_only();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_source_type'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_source_document_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_owner_person_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_chassis_number'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_phone_numbers_source_type'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_source_document_id'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_phone_number'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_associated_person_id'), table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index(op.f('ix_shared_records_shared_by'), table_name='shared_records')
    op.drop_index(op.f('ix_shared_records_data_request_id'), table_name='shared_records')
    op.drop_table('shared_records')
    op.drop_index(op.f('ix_persons_status'), table_name='persons')
    op.drop_index(op.f('ix_persons_source_type'), table_name='persons')
    op.drop_index(op.f('ix_persons_source_document_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_risk_level'), table_name='persons')
    op.drop_index(op.f('ix_persons_person_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_national_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_full_name'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_locations_source_type'), table_name='locations')
    op.drop_index(op.f('ix_locations_source_document_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_city'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_extracted_entities_rejected'), table_name='extracted_entities')
    op.drop_index(op.f('ix_extracted_entities_entity_type'), table_name='extracted_entities')
    op.drop_index(op.f('ix_extracted_entities_document_id'), table_name='extracted_entities')
    op.drop_index(op.f('ix_extracted_entities_confirmed_by'), table_name='extracted_entities')
    op.drop_index(op.f('ix_extracted_entities_confirmed'), table_name='extracted_entities')
    op.drop_index(op.f('ix_extracted_entities_case_id'), table_name='extracted_entities')
    op.drop_table('extracted_entities')
    op.drop_index(op.f('ix_ml_predictions_status'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_evidence_strength'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_entity_b_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_entity_a_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_created_at'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_case_id'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_documents_uploaded_by'), table_name='documents')
    op.drop_index(op.f('ix_documents_processing_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_data_requests_status'), table_name='data_requests')
    op.drop_index(op.f('ix_data_requests_source_authority_id'), table_name='data_requests')
    op.drop_index(op.f('ix_data_requests_requesting_officer_id'), table_name='data_requests')
    op.drop_index(op.f('ix_data_requests_requesting_authority_id'), table_name='data_requests')
    op.drop_index(op.f('ix_data_requests_request_number'), table_name='data_requests')
    op.drop_index(op.f('ix_data_requests_created_at'), table_name='data_requests')
    op.drop_index(op.f('ix_data_requests_case_id'), table_name='data_requests')
    op.drop_table('data_requests')
    op.drop_index(op.f('ix_case_entities_entity_type'), table_name='case_entities')
    op.drop_index(op.f('ix_case_entities_entity_id'), table_name='case_entities')
    op.drop_index(op.f('ix_case_entities_case_id'), table_name='case_entities')
    op.drop_table('case_entities')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_case_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_priority'), table_name='cases')
    op.drop_index(op.f('ix_cases_investigating_officer_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_fir_number'), table_name='cases')
    op.drop_index(op.f('ix_cases_crime_type'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_index(op.f('ix_cases_authority_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_keycloak_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_badge_id'), table_name='users')
    op.drop_index(op.f('ix_users_authority_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_authorities_type'), table_name='authorities')
    op.drop_index(op.f('ix_authorities_parent_authority_id'), table_name='authorities')
    op.drop_index(op.f('ix_authorities_name'), table_name='authorities')
    op.drop_table('authorities')
    # ### end Alembic commands ###
